version: "3.3"
services:
    db:
        image: postgres
        container_name: qna_postgres
        # restart: always
        environment: 
            POSTGRES_PASSWORD: process.env.PASSWORD
            POSTGRES_USER: postgres
        volumes: 
            # - data:/var/lib/postgresql/data
            - ./pgdata/:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    qna_server:
        # image: susyqinqinyang/qna_server
        build: ./server/
        image: qna_server
        container_name: qna_server
        depends_on:
            - db
        ports:
            # - "3555:3555"
            - "80:3555"


# volumes:
#     data:
#         external:
#             name: pgdata
            


